# Generated by Django 6.0.1 on 2026-01-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf_responsavel', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Responsável')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('escola_publica', models.BooleanField(default=True, verbose_name='Estuda em Escola Pública?')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações (Saúde/Social)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
