# Generated by Django 6.0.1 on 2026-01-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Turma (Ex: Violão Iniciante)')),
                ('professor', models.CharField(max_length=100, verbose_name='Nome do Professor/Voluntário')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado')], max_length=3, verbose_name='Dia da Semana')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('alunos', models.ManyToManyField(blank=True, related_name='turmas', to='academico.aluno', verbose_name='Alunos Matriculados')),
            ],
            options={
                'verbose_name': 'Turma/Oficina',
                'verbose_name_plural': 'Turmas/Oficinas',
            },
        ),
    ]
