# Generated by Django 6.0.1 on 2026-01-08 22:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data da Aula')),
                ('conteudo', models.TextField(blank=True, null=True, verbose_name='Conteúdo Ministrado')),
                ('alunos_presentes', models.ManyToManyField(blank=True, to='academico.aluno', verbose_name='Alunos Presentes')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Diário de Aula / Chamada',
                'verbose_name_plural': 'Diários de Aula / Chamadas',
                'ordering': ['-data'],
            },
        ),
    ]
