# Generated by Django 6.0.1 on 2026-01-08 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0003_aula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome (Ex: Violão Tagima)')),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº de Série')),
                ('codigo_interno', models.CharField(max_length=20, unique=True, verbose_name='Cód. Etiqueta (Patrimônio)')),
                ('estado', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom Estado'), ('REGULAR', 'Regular (Marcas de uso)'), ('DANIFICADO', 'Danificado (Precisa reparo)'), ('SUCATA', 'Sucata/Inutilizável')], default='BOM', max_length=20, verbose_name='Estado de Conservação')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EMPRESTADO', 'Emprestado'), ('MANUTENCAO', 'Em Manutenção')], default='DISPONIVEL', max_length=20)),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor (R$)')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField(auto_now_add=True, verbose_name='Data de Retirada')),
                ('data_prevista', models.DateField(verbose_name='Previsão de Devolução')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Devolvido em')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs. na retirada (Ex: já estava arranhado)')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.aluno')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.instrumento')),
            ],
            options={
                'verbose_name': 'Empréstimo de Instrumento',
                'verbose_name_plural': 'Controle de Empréstimos',
            },
        ),
    ]
