# Generated by Django 6.0.1 on 2026-01-08 23:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Razão Social')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica/Empresa')], default='PF', max_length=2)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Doador Ativo?')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doador / Parceiro',
                'verbose_name_plural': 'Doadores / Parceiros',
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data da Doação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('BOLETO', 'Boleto'), ('OUTRO', 'Outros')], default='PIX', max_length=20)),
                ('destino', models.CharField(blank=True, help_text='Ex: Projeto Música, Manutenção, Livre', max_length=100, null=True, verbose_name='Destino (Opcional)')),
                ('doador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.doador', verbose_name='Quem doou?')),
            ],
            options={
                'verbose_name': 'Entrada de Doação',
                'verbose_name_plural': 'Entradas de Doações',
            },
        ),
    ]
